services:
  - type: web
    name: habit-tracker-notifications
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7985172630:AAFTN9xGM2C-s0ni07VHOcCCZiyL3XbDh4o
    rootDir: server

